import { Topbar } from "@/components/topbar";
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";

export const metadata: Metadata = {
  title: "Live Golf Tournament Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="root h-screen relative">
          <Image
            src={"/bg.jpg"}
            alt="background"
            width={1920}
            height={1080}
            className="absolute w-full h-screen -z-10 object-cover"
          />
          <div className="relative overflow-y-auto h-screen bg-linear-to-t from-background via-accent/90 to-accent/10 z-10">
            <Topbar />
            <div className="px-6 grid-cols-7 grid gap-6 h-[calc(100vh-106px)]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
